### ISSUE TITLE
FATAL ERROR: Unexpected end of file has occurred. The following elements are not closed: softwarelists. Line 1251074, position 1.

### ISSUE THREAD

**Issue by paulmortlock** [sam-ludlow/mame-ao#16]
Creating machine performance caches......done
Existing SQLite database is old version re-creating: C:\Mame-ao\0264\_software.sqlite
Loading XML C:\Mame-ao\0264\_software.xml ...
!!! FATAL ERROR: Unexpected end of file has occurred. The following elements are not closed: softwarelists. Line 1251074, position 1.

System.Xml.XmlException: Unexpected end of file has occurred. The following elements are not closed: softwarelists. Line 1251074, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ThrowUnclosedElements()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XElement.ReadElementFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XElement.Load(String uri, LoadOptions options)
   at Spludlow.MameAO.Database.DatabaseFromXML(String xmlFilename, String sqliteFilename, String assemblyVersion)
   at Spludlow.MameAO.Database.InitializeSoftware(String xmlFilename, String databaseFilename, String assemblyVersion)
   at Spludlow.MameAO.MameAOProcessor.Initialize()
   at Spludlow.MameAO.MameAOProcessor.Run()

**Comment by sam-ludlow** [comment]
Hello @paulmortlock 

As you previously ran out of RAM it left some files in a mess.

Do the following:

- Delete all files beginning with underscore see below screenshot
- Ensure you have RAM free, the first run peaks at 1.4GB, maybe reboot and don't start any other software
- Run mame-ao again - you can keep an eye on task manager to see the RAM usage.

NOTE: After first run mame-ao will sit on about 400MB.

Cheers
Sam

![image](https://github.com/sam-ludlow/mame-ao/assets/47115020/346716b2-e990-4ef8-a8df-484cf6ff2b8f)

**Comment by paulmortlock** [comment]
Cheers Sam I will try that out.

**Comment by paulmortlock** [comment]
Fantastic works so well.

**Comment by sam-ludlow** [comment]
Glad you got it working, closing ticket. Cheers
