### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by albertobelardi** [sam-ludlow/mame-ao#47]
```
Ready to load: https://archive.org/metadata/mame-sl-chd-sgi_mips
Ready to load: https://archive.org/metadata/mame-sl-chd-sgi_mips_hdd
Ready to load: https://archive.org/metadata/mame-sl-chd-snes_vkun
Ready to load: https://archive.org/metadata/mame-sl-chd-softbox
Ready to load: https://archive.org/metadata/mame-sl-chd-v1050_hdd
Ready to load: https://archive.org/metadata/mame-sl-chd-vis
Ready to load: https://archive.org/metadata/mame-sl-chd-vsmile_cd
Ready to load: https://archive.org/metadata/mame-software-list-chds-2
=======================================================================================================================
=                                                        MAME                                                         =
=                  https://github.com/mamedev/mame/releases/download/mameROM S/mameROM Sb_64bit.exe                   =
=======================================================================================================================
Downloading MAME binaries https://github.com/mamedev/mame/releases/download/mameROM S/mameROM Sb_64bit.exe ...
!!! FATAL ERROR: The request was aborted: The connection was closed unexpectedly.

System.Net.WebException: The request was aborted: The connection was closed unexpectedly.
   at System.Net.HttpWebRequest.GetResponse()
   at Spludlow.MameAO.Tools.Download(String url, String filename, Int64 progressSize, Int32 timeoutMinutes, TaskInfo taskInfo)
   at Spludlow.MameAO.Tools.Download(String url, String filename, Int64 progressSize, Int32 timeoutMinutes)
   at Spludlow.MameAO.MameAOProcessor.Initialize()
   at Spludlow.MameAO.MameAOProcessor.Run()

If you want to submit an error report please copy and paste the text from here.
Select All (Ctrl+A) -> Copy (Ctrl+C) -> notepad -> paste (Ctrl+V)

Report issues here https://github.com/sam-ludlow/mame-ao/issues

Press any key to continue, program has crashed and will exit.
```

**Comment by sam-ludlow** [comment]
Hello @albertobelardi 

You're running an old version that won't start due to changes in archive.org.

Please download the latest from: https://github.com/sam-ludlow/mame-ao/releases/latest

Replace your existing files with what's in the ZIP, mame-ao.exe, UI.html ...

Cheers
Sam
