### ISSUE TITLE
The remote server returned an error: (401) unauthorized.

### ISSUE THREAD

**Issue by vsky61** [sam-ludlow/mame-ao#49]
```
1.94
'##::::'##::::'###::::'##::::'##:'########:::::::'###:::::'#######::
 ###::'###:::'## ##::: ###::'###: ##.....:::::::'## ##:::'##.... ##:
 ####'####::'##:. ##:: ####'####: ##:::::::::::'##:. ##:: ##:::: ##:
 ## ### ##:'##:::. ##: ## ### ##: ######::::::'##:::. ##: ##:::: ##:
 ##. #: ##: #########: ##. #: ##: ##...::::::: #########: ##:::: ##:
 ##:.:: ##: ##.... ##: ##:.:: ##: ##:::::::::: ##.... ##: ##:::: ##:
 ##:::: ##: ##:::: ##: ##:::: ##: ########:::: ##:::: ##:. #######::
..:::::..::..:::::..::..:::::..::........:::::..:::::..:::.......:::

       Please wait the first time it has to prepare the data

         The Web User Interface will pop up when ready

              See the README for more information
             https://github.com/sam-ludlow/mame-ao

#######################################################################################################################
#                                                    Initializing                                                     #
#######################################################################################################################
-----------------------------------------------------------------------------------------------------------------------
-                  !!! You can save a lot of disk space by enabling symbolic links, see the README.                   -
-----------------------------------------------------------------------------------------------------------------------
Downloading https://api.github.com/repos/sam-ludlow/mame-ao ......done
Downloading https://api.github.com/repos/sam-ludlow/mame-ao/releases ......done
Downloading https://api.github.com/repos/sam-ludlow/mame-ao/releases/latest ......done
Downloading https://api.github.com/repos/mamedev/mame ......done
Downloading https://api.github.com/repos/mamedev/mame/releases ......done
Downloading https://api.github.com/repos/mamedev/mame/releases/latest ......done
Downloading https://api.github.com/repos/AntoPISA/MAME_Dats ......done
Downloading https://api.github.com/repos/AntoPISA/MAME_Dats/releases ......done
Downloading https://api.github.com/repos/AntoPISA/MAME_SupportFiles ......done
Downloading https://api.github.com/repos/AntoPISA/MAME_SupportFiles/releases ......done
=======================================================================================================================
=                                                      MAME 0269                                                      =
=                   https://github.com/mamedev/mame/releases/download/mame0269/mame0269b_64bit.exe                    =
=======================================================================================================================
Creating machine performance caches......done
Creating software performance caches......done
Getting all database SHA1s......done.
=======================================================================================================================
=                                                   Machine Genres                                                    =
=               https://raw.githubusercontent.com/AntoPISA/MAME_SupportFiles/main/catver.ini/catver.ini               =
=======================================================================================================================
Downloading https://raw.githubusercontent.com/AntoPISA/MAME_SupportFiles/main/catver.ini/catver.ini ......done
Loading Genres......done
Version:        0.268

#######################################################################################################################
#                                         Remote Listener ready for commands                                          #
#                                               http://localhost:12380/                                               #
#                            e.g. http://localhost:12380/api/command?line=a2600 et -window                            #
#######################################################################################################################

#######################################################################################################################
#                                              Shell ready for commands                                               #
#######################################################################################################################

MAME Shell (0269)>
#######################################################################################################################
#                                               Remote command recieved                                               #
#                                                      bbusters                                                       #
#######################################################################################################################

#######################################################################################################################
#                                                  Asset Acquisition                                                  #
#######################################################################################################################

Require:        9/2/2024 10:44:02 AM    machine rom     bbusters        bbusters        0b6e06adf9c181d7aef28f781efbdd2c225fe81e        True    bb-3.k10
Require:        9/2/2024 10:44:02 AM    machine rom     bbusters        bbusters        b7ac0c6ea3738d560a5be75aed286821de918808        True    bb-5.k12
Require:        9/2/2024 10:44:02 AM    machine rom     bbusters        bbusters        0958579681bda81bcf48d020a14bc147c1e575f1        True    bb-2.k8
Require:        9/2/2024 10:44:02 AM    machine rom     bbusters        bbusters        e56ca92965e8954b613ba4b0e3975e3a12840c30        True    bb-4.k11
Require:        9/2/2024 10:44:02 AM    machine rom     bbusters        bbusters        4c6b212f59389bdf4388893d2030493b110ac087        True    bb-1.e6
Require:        9/2/2024 10:44:02 AM    machine rom     bbusters        bbusters        567c25a6d96407259c64061d674305e4117d9fa4        True    bb-10.l9
Require:        9/2/2024 10:44:02 AM    machine rom     bbusters        bbusters        80392947e3a1831c3ee80139f6f3bdc3bafa4f0d        True    bb-f11.m16
Require:        9/2/2024 10:44:02 AM    machine rom     bbusters        bbusters        5c0435f1ce76b584fa8d154d7617d73c7ab5f62f        True    bb-f12.m13
Require:        9/2/2024 10:44:02 AM    machine rom     bbusters        bbusters        dd0f630c52076e0d330f47931e68a3ae9a401078        True    bb-f13.m12
Require:        9/2/2024 10:44:02 AM    machine rom     bbusters        bbusters        1f27a528e6f89fe56a7342c4f1ff733da0a09327        True    bb-f14.m11
Require:        9/2/2024 10:44:02 AM    machine rom     bbusters        bbusters        820898693b878c4423de9c244f943d39ea69515e        True    bb-f21.l10
Require:        9/2/2024 10:44:02 AM    machine rom     bbusters        bbusters        d19172d6515ab9793c98de75d6e41687e61a408d        True    bb-f22.l12
Require:        9/2/2024 10:44:02 AM    machine rom     bbusters        bbusters        92be860a7191e7473c42aa2da981eda873219d3d        True    bb-f23.l13
Require:        9/2/2024 10:44:02 AM    machine rom     bbusters        bbusters        2213c17651b6c023a456447f352b0739439f913a        True    bb-f24.l15
Require:        9/2/2024 10:44:02 AM    machine rom     bbusters        bbusters        3c99b557b2af30ff0fbc8a7dc6c40448c4f327db        True    bb-back1.m4
Require:        9/2/2024 10:44:02 AM    machine rom     bbusters        bbusters        1e2c56f4c24793f806d7b366b92edc03145ae94c        True    bb-back2.m6
Require:        9/2/2024 10:44:02 AM    machine rom     bbusters        bbusters        736f9634fe054ea68a2aa90a743bd0dc320f23c9        True    bb-6.e7
Require:        9/2/2024 10:44:02 AM    machine rom     bbusters        bbusters        736f9634fe054ea68a2aa90a743bd0dc320f23c9        True    bb-7.h7
Require:        9/2/2024 10:44:02 AM    machine rom     bbusters        bbusters        736f9634fe054ea68a2aa90a743bd0dc320f23c9        True    bb-8.a14
Require:        9/2/2024 10:44:02 AM    machine rom     bbusters        bbusters        736f9634fe054ea68a2aa90a743bd0dc320f23c9        True    bb-9.c14
Require:        9/2/2024 10:44:02 AM    machine rom     bbusters        bbusters        26a612191a0aa614c090203485aba17c99c763ee        True    bb-pcma.l5
Require:        9/2/2024 10:44:02 AM    machine rom     bbusters        bbusters        0f7e94532cc14852ca12c1b792e5479667af899e        True    bb-pcmb.l3
Downloading https://archive.org/metadata/mame-merged ......done
Downloading size:2.6 Megabytes (MiB) url:https://archive.org/download/mame-merged/mame-merged/bbusters.zip ...
!!! WORKER ERROR: The remote server returned an error: (401) Unauthorized.

System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.GetResponse()
   at Spludlow.MameAO.Tools.Download(String url, String filename, Int64 expectedSize)
   at Spludlow.MameAO.Place.DownloadImportFiles(String url, Int64 expectedSize, String[] info)
   at Spludlow.MameAO.Place.PlaceMachineRoms(String mainMachineName)
   at Spludlow.MameAO.Place.PlaceAssets(String machineName, String softwareName)
   at Spludlow.MameAO.MameAOProcessor.RunLine(String line)
   at Spludlow.MameAO.MameAOProcessor.<>c__DisplayClass9_0.<RunLineTask>b__0()

If you want to submit an error report please copy and paste the text from here.
Select All (Ctrl+A) -> Copy (Ctrl+C) -> notepad -> paste (Ctrl+V)

Report issues here https://github.com/sam-ludlow/mame-ao/issues

#######################################################################################################################
#                                               Remote command recieved                                               #
#                                                      bbusters                                                       #
#######################################################################################################################

#######################################################################################################################
#                                                  Asset Acquisition                                                  #
#######################################################################################################################

Require:        9/2/2024 10:44:19 AM    machine rom     bbusters        bbusters        0b6e06adf9c181d7aef28f781efbdd2c225fe81e        True    bb-3.k10
Require:        9/2/2024 10:44:19 AM    machine rom     bbusters        bbusters        b7ac0c6ea3738d560a5be75aed286821de918808        True    bb-5.k12
Require:        9/2/2024 10:44:19 AM    machine rom     bbusters        bbusters        0958579681bda81bcf48d020a14bc147c1e575f1        True    bb-2.k8
Require:        9/2/2024 10:44:19 AM    machine rom     bbusters        bbusters        e56ca92965e8954b613ba4b0e3975e3a12840c30        True    bb-4.k11
Require:        9/2/2024 10:44:19 AM    machine rom     bbusters        bbusters        4c6b212f59389bdf4388893d2030493b110ac087        True    bb-1.e6
Require:        9/2/2024 10:44:19 AM    machine rom     bbusters        bbusters        567c25a6d96407259c64061d674305e4117d9fa4        True    bb-10.l9
Require:        9/2/2024 10:44:19 AM    machine rom     bbusters        bbusters        80392947e3a1831c3ee80139f6f3bdc3bafa4f0d        True    bb-f11.m16
Require:        9/2/2024 10:44:19 AM    machine rom     bbusters        bbusters        5c0435f1ce76b584fa8d154d7617d73c7ab5f62f        True    bb-f12.m13
Require:        9/2/2024 10:44:19 AM    machine rom     bbusters        bbusters        dd0f630c52076e0d330f47931e68a3ae9a401078        True    bb-f13.m12
Require:        9/2/2024 10:44:19 AM    machine rom     bbusters        bbusters        1f27a528e6f89fe56a7342c4f1ff733da0a09327        True    bb-f14.m11
Require:        9/2/2024 10:44:19 AM    machine rom     bbusters        bbusters        820898693b878c4423de9c244f943d39ea69515e        True    bb-f21.l10
Require:        9/2/2024 10:44:19 AM    machine rom     bbusters        bbusters        d19172d6515ab9793c98de75d6e41687e61a408d        True    bb-f22.l12
Require:        9/2/2024 10:44:19 AM    machine rom     bbusters        bbusters        92be860a7191e7473c42aa2da981eda873219d3d        True    bb-f23.l13
Require:        9/2/2024 10:44:19 AM    machine rom     bbusters        bbusters        2213c17651b6c023a456447f352b0739439f913a        True    bb-f24.l15
Require:        9/2/2024 10:44:19 AM    machine rom     bbusters        bbusters        3c99b557b2af30ff0fbc8a7dc6c40448c4f327db        True    bb-back1.m4
Require:        9/2/2024 10:44:19 AM    machine rom     bbusters        bbusters        1e2c56f4c24793f806d7b366b92edc03145ae94c        True    bb-back2.m6
Require:        9/2/2024 10:44:19 AM    machine rom     bbusters        bbusters        736f9634fe054ea68a2aa90a743bd0dc320f23c9        True    bb-6.e7
Require:        9/2/2024 10:44:19 AM    machine rom     bbusters        bbusters        736f9634fe054ea68a2aa90a743bd0dc320f23c9        True    bb-7.h7
Require:        9/2/2024 10:44:19 AM    machine rom     bbusters        bbusters        736f9634fe054ea68a2aa90a743bd0dc320f23c9        True    bb-8.a14
Require:        9/2/2024 10:44:19 AM    machine rom     bbusters        bbusters        736f9634fe054ea68a2aa90a743bd0dc320f23c9        True    bb-9.c14
Require:        9/2/2024 10:44:19 AM    machine rom     bbusters        bbusters        26a612191a0aa614c090203485aba17c99c763ee        True    bb-pcma.l5
Require:        9/2/2024 10:44:19 AM    machine rom     bbusters        bbusters        0f7e94532cc14852ca12c1b792e5479667af899e        True    bb-pcmb.l3
Downloading size:2.6 Megabytes (MiB) url:https://archive.org/download/mame-merged/mame-merged/bbusters.zip ...
!!! WORKER ERROR: The remote server returned an error: (401) Unauthorized.

System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.GetResponse()
   at Spludlow.MameAO.Tools.Download(String url, String filename, Int64 expectedSize)
   at Spludlow.MameAO.Place.DownloadImportFiles(String url, Int64 expectedSize, String[] info)
   at Spludlow.MameAO.Place.PlaceMachineRoms(String mainMachineName)
   at Spludlow.MameAO.Place.PlaceAssets(String machineName, String softwareName)
   at Spludlow.MameAO.MameAOProcessor.RunLine(String line)
   at Spludlow.MameAO.MameAOProcessor.<>c__DisplayClass9_0.<RunLineTask>b__0()

If you want to submit an error report please copy and paste the text from here.
Select All (Ctrl+A) -> Copy (Ctrl+C) -> notepad -> paste (Ctrl+V)

Report issues here https://github.com/sam-ludlow/mame-ao/issues
```

**Comment by sam-ludlow** [comment]
Hello @vsky61 

Looks like logging in is a requirement now. I best look at that.

![image](https://github.com/user-attachments/assets/6b72ed0c-1f94-4807-9319-d2e93a57dbbc)

**Comment by sam-ludlow** [comment]
Hello @vsky61 

Archive.org authentication is now implemented in version 1.95.

It should self update or download latest here https://github.com/sam-ludlow/mame-ao/releases/latest

You have to enter your creds when MAME-AO starts now. See the README

I'll make it more user friendly at a later date but it down work for now.

Cheers
Sam

**Comment by sam-ludlow** [comment]
I've not worked out how long the auth cookie lasts for so if anyone gets 401/403 try deleting the cookie from the cacahe, you will need to enter archive.org  creds again.

Note software ROM is still broken.

![image](https://github.com/user-attachments/assets/221a312e-6da1-42e0-b745-f38eb53a2778)

**Comment by paulmortlock** [comment]
![image](https://github.com/user-attachments/assets/7a63c39b-47d2-4cd2-a644-e33ca21b4380)

**Comment by paulmortlock** [comment]
![image](https://github.com/user-attachments/assets/64375ec0-afc8-4f2f-a738-b1dd394e3473)

**Comment by sam-ludlow** [comment]
Hello @vsky61  @paulmortlock 

Software ROM download fixed in 1.96

Cheers
Sam

**Comment by sam-ludlow** [comment]
@paulmortlock `sp3eata bhcopa` nice one.

**Comment by paulmortlock** [comment]
Fantastic work

**Comment by sam-ludlow** [comment]
Closing archive.org has settled down now and MAME-AO is using the new archive.org authentication.
