### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by ssphaneuf** [sam-ludlow/mame-ao#64]
Enter your Archive.org username:
myarchive
Enter your Archive.org password:
fake123
Downloading https://api.github.com/repos/sam-ludlow/mame-ao ......done
Downloading https://api.github.com/repos/sam-ludlow/mame-ao/releases ......done
Downloading https://api.github.com/repos/sam-ludlow/mame-ao/releases/latest ......done
Downloading https://api.github.com/repos/mamedev/mame ......done
Downloading https://api.github.com/repos/mamedev/mame/releases ......done
Downloading https://api.github.com/repos/mamedev/mame/releases/latest ......done
Downloading https://api.github.com/repos/AntoPISA/MAME_Dats ......done
Downloading https://api.github.com/repos/AntoPISA/MAME_Dats/releases ......done
Downloading https://api.github.com/repos/AntoPISA/MAME_SupportFiles ......done
Downloading https://api.github.com/repos/AntoPISA/MAME_SupportFiles/releases ......done
=======================================================================================================================
=                                                      MAME 0271                                                      =
=                   https://github.com/mamedev/mame/releases/download/mame0271/mame0271b_64bit.exe                    =
=======================================================================================================================
Downloading MAME binaries https://github.com/mamedev/mame/releases/download/mame0271/mame0271b_64bit.exe .................................................................................................done.
Extracting MAME binaries C:\MAMEAO\0271\mame.exe ......done.
Extracting MAME machine XML C:\MAMEAO\0271\_machine.xml ......done.
Loading XML C:\MAMEAO\0271\_machine.xml ......done.
Importing XML mame ......done.
Adding extra data columns mame ......done.
Creating SQLite mame ...mame...machine...rom...device_ref...sample...input...driver...feature...softwarelist...disk...ao_info......done.
Creating machine performance caches......done
Extracting MAME software XML C:\MAMEAO\0271\_software.xml ......done.
Loading XML C:\MAMEAO\0271\_software.xml ......done.
Importing XML softwarelists ......done.
Adding extra data columns softwarelists ......done.
Creating SQLite softwarelists ...softwarelists...softwarelist...software...part...dataarea...rom...sharedfeat...diskarea...disk...ao_info......done.
Creating software performance caches......done
Getting all database SHA1s......done.
=======================================================================================================================
=                                                   Machine Genres                                                    =
=               https://raw.githubusercontent.com/AntoPISA/MAME_SupportFiles/main/catver.ini/catver.ini               =
=======================================================================================================================
Downloading https://raw.githubusercontent.com/AntoPISA/MAME_SupportFiles/main/catver.ini/catver.ini ......done
Loading Genres......done
Update Machines database with genre IDs ......done
Version:        0.270

#######################################################################################################################
#                                         Remote Listener ready for commands                                          #
#                                               http://localhost:12380/                                               #
#                            e.g. http://localhost:12380/api/command?line=a2600 et -window                            #
#######################################################################################################################

#######################################################################################################################
#                                              Shell ready for commands                                               #
#######################################################################################################################

MAME Shell (0271)>
#######################################################################################################################
#                                               Remote command recieved                                               #
#                                                       88games                                                       #
#######################################################################################################################

#######################################################################################################################
#                                                  Asset Acquisition                                                  #
#######################################################################################################################

Require:        11/5/2024 6:24:48 PM    machine rom     88games 88games 95572686bef48b5c1ce1dedf0afc891d92aff00d
        True    861m01.k18
Require:        11/5/2024 6:24:48 PM    machine rom     88games 88games 6c801b274e87eaff7f40148381ade5b38120cc12
        True    861m02.k16
Require:        11/5/2024 6:24:48 PM    machine rom     88games 88games 749dc98f8740beee1383f85effc9336081315f4b
        True    861d01.d9
Require:        11/5/2024 6:24:48 PM    machine rom     88games 88games e3667839f8ae3699236da3e312c20d571db38670
        True    861a08.a
Require:        11/5/2024 6:24:48 PM    machine rom     88games 88games b3842c8dc60975cc71812df098f29b4571b18120
        True    861a08.c
Require:        11/5/2024 6:24:48 PM    machine rom     88games 88games 3614b78c2100f135ea0701409ce279a423decb23
        True    861a09.a
Require:        11/5/2024 6:24:48 PM    machine rom     88games 88games 7d5d88e1492ed361dc7b2135595393b89b9cb5b1
        True    861a09.c
Require:        11/5/2024 6:24:48 PM    machine rom     88games 88games 6b4037eff6d209fec29d05f1071ed3bf9c2bd098
        True    861a08.b
Require:        11/5/2024 6:24:48 PM    machine rom     88games 88games 3fb5fe512c2497160a66e9de0cd45c38dfe46410
        True    861a08.d
Require:        11/5/2024 6:24:48 PM    machine rom     88games 88games b53da3f29c9aeb59933dc3a8214cc1314e21000b
        True    861a09.b
Require:        11/5/2024 6:24:48 PM    machine rom     88games 88games 6ca54948a02c91543b7e595641b0edc2564f83ff
        True    861a09.d
Require:        11/5/2024 6:24:48 PM    machine rom     88games 88games 6eb2a292d574dee06e214e61c0e08fa233ac68e8
        True    861a05.a
Require:        11/5/2024 6:24:48 PM    machine rom     88games 88games 98ac364db4b2c5682a299f4d2a288ebc8a303b1f
        True    861a05.e
Require:        11/5/2024 6:24:48 PM    machine rom     88games 88games 11010727db8c71650c5b9df5340f9bc412435d11
        True    861a06.a
Require:        11/5/2024 6:24:48 PM    machine rom     88games 88games c740a814a3e203348b269a70256e01fe2a914118
        True    861a06.e
Require:        11/5/2024 6:24:48 PM    machine rom     88games 88games dad6b127761889aac198014139cc524a4cea32e7
        True    861a05.b
Require:        11/5/2024 6:24:48 PM    machine rom     88games 88games a3f10720151f538cf1bec5953a4212bc96ba42fe
        True    861a05.f
Require:        11/5/2024 6:24:48 PM    machine rom     88games 88games cc121c5742428e2613b7da2d8357f15e897161ca
        True    861a06.b
Require:        11/5/2024 6:24:48 PM    machine rom     88games 88games 77bac66489e7fc2ddd714fc684e79d70b089ee84
        True    861a06.f
Require:        11/5/2024 6:24:48 PM    machine rom     88games 88games 234714212dd7288a5128d36c96cca5b62e86d37d
        True    861a05.c
Require:        11/5/2024 6:24:48 PM    machine rom     88games 88games fc8923819fa7f3d02b4d159aea45cb5d1a80f1b0
        True    861a05.g
Require:        11/5/2024 6:24:48 PM    machine rom     88games 88games 8b69a0ac90f32cea31f8c7fcd985ad58fb6c009e
        True    861a06.c
Require:        11/5/2024 6:24:48 PM    machine rom     88games 88games 35088bf7f6acd2bc95f673a2816b35238d611308
        True    861a06.g
Require:        11/5/2024 6:24:48 PM    machine rom     88games 88games 2c123fd08cb9626cf309e7320fe2eb99e4b483fb
        True    861a05.d
Require:        11/5/2024 6:24:48 PM    machine rom     88games 88games c7d3531eb65abd51ae4e6f55244d674353d23d36
        True    861a05.h
Require:        11/5/2024 6:24:48 PM    machine rom     88games 88games a6fa0502ceb6862e7b1e4815326e268fd6511881
        True    861a06.d
Require:        11/5/2024 6:24:48 PM    machine rom     88games 88games 905814ce708d80fd4d1a398f60faa0bc680fccaf
        True    861a06.h
Require:        11/5/2024 6:24:48 PM    machine rom     88games 88games d98a81bfa4bba73805f0236f8a80da130fcb378d
        True    861a04.a
Require:        11/5/2024 6:24:48 PM    machine rom     88games 88games 5133d8f6622796ed6b9e6a0d0f1df28f00331fc7
        True    861a04.b
Require:        11/5/2024 6:24:48 PM    machine rom     88games 88games f73f88af33387d73b4262e8652507e699926fabe
        True    861a04.c
Require:        11/5/2024 6:24:48 PM    machine rom     88games 88games 77dd31163c8431416ab0593f084719c914222912
        True    861a04.d
Require:        11/5/2024 6:24:48 PM    machine rom     88games 88games d27e8e180f19d2b160f18c79520a77182a62218c
        True    861.g3
Require:        11/5/2024 6:24:48 PM    machine rom     88games 88games 9df63e004a4f52768331dfb3c3889301ac174ea1
        True    861a07.a
Require:        11/5/2024 6:24:48 PM    machine rom     88games 88games 74ba58f1664abd1491598c1a9467f470304fa430
        True    861a07.b
Require:        11/5/2024 6:24:48 PM    machine rom     88games 88games b5a8f7122356dd72a97e71b480835ba500116aaf
        True    861a07.c
Require:        11/5/2024 6:24:48 PM    machine rom     88games 88games c1410f6c7a23aa0c213878a6531d3e7eb966b0a4
        True    861a07.d
Downloading https://archive.org/metadata/mame-merged ......done
Downloading size:851 Kilobytes (KiB) url:https://archive.org/download/mame-merged/mame-merged/88games.zip ...
!!! WORKER ERROR: The remote server returned an error: (403) Forbidden.

System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.GetResponse()
   at Spludlow.MameAO.Tools.Download(String url, String filename, Int64 expectedSize)
   at Spludlow.MameAO.Place.DownloadImportFiles(String url, Int64 expectedSize, String[] info)
   at Spludlow.MameAO.Place.PlaceMachineRoms(String mainMachineName)
   at Spludlow.MameAO.Place.PlaceAssets(String machineName, String softwareName)
   at Spludlow.MameAO.MameAOProcessor.RunLine(String line)
   at Spludlow.MameAO.MameAOProcessor.<>c__DisplayClass9_0.<RunLineTask>b__0()

If you want to submit an error report please copy and paste the text from here.
Select All (Ctrl+A) -> Copy (Ctrl+C) -> notepad -> paste (Ctrl+V)

Report issues here https://github.com/sam-ludlow/mame-ao/issues

**Comment by ssphaneuf** [comment]
Think it was a login error.
